#include <iostream>
#include <cmath>
#include "TFile.h"
#include "TTree.h"
#include "TTree.h"
#include "TH1.h"
#include <TH2.h>
#include <TEfficiency.h>
#include <stdio.h>


using namespace std;

namespace {
  //TODO make this configurable
  string signalSelection("Wmunu");//This can be: "Zmumu", "Zee","Wmunu", "Wenu"
  float GeV(0.001);
  int offCol(kBlue);
  int cellCol(kYellow+1);
  int mhtCol(kRed);
  int pufitCol(kCyan+1);
  int mhtPcellCol(kOrange-3);
}

void treeToHist()
{
  //in progress//TODO Geting met 'types' string name/s to put in histograms
  //in progressvector<string> metTypes;
  //in progress//TODO make this configurable
  //in progressmetTypes.push_back("cell");
  //in progressmetTypes.push_back("mht");
  //in progressmetTypes.push_back("pufit");
  //in progressmetTypes.push_back("offline");

  //in progress//TODO Getting met 'types' string name/s to put in histograms
  //in progressvector<string> signalSel;
  //in progress//TO-DO make this configurable
  //in progresssignalSel.push_back("Zee");
  //in progresssignalSel.push_back("Zmumu");
  //in progress//signalSel.push_back("Wenu");
  //in progress//signalSel.push_back("Wmumu");

  //read the Tree generated by the MakeTree algorithm and make histograms
  TFile *f = new TFile("metTree.root");
  TTree *t_metTree = (TTree*)f->Get("metTree");
  float offlineMET;
  float hlt_cell_met;
  float hlt_mht_met;
  float hlt_topoCluster_met;
  float hlt_pufit_met;
  float hlt_pueta_met;

  unsigned long long int eventNumber;
  uint32_t runNumber;
  uint32_t lumiBlock;
  uint32_t bunchCrossingID;
  float actualMu;
  float averageMu;
  int nPrimaryVtx;

  int distanceFromFront;
  int distanceFromTail; 

  bool passWenu;
  bool passWmunu;
  bool passZee;
  bool passZmumu;

  //TODO: PRIORITY make trigger work with a list of triggers(implement on NtupleMaker)
  bool pass_HLT_xe100_L1XE50;
  bool pass_HLT_xe110_mht_L1XE50;
  bool pass_HLT_xe160_tc_lcw_L1XE50;
  bool pass_HLT_xe140_pufit_L1XE50;
  bool pass_HLT_xe140_pueta_L1XE50;
  bool pass_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50;

  t_metTree->SetBranchAddress("offlineMET",&offlineMET);
  //Cell
  t_metTree->SetBranchAddress("hlt_cell_met",&hlt_cell_met);
  //mht (tc_mht)  
  t_metTree->SetBranchAddress("hlt_mht_met",&hlt_mht_met);
  //Topocluster (tc_lcw)  
  t_metTree->SetBranchAddress("hlt_topoCluster_met",&hlt_topoCluster_met);
  //Topocluster pileup fit (tc_lcw_pufit) 
  t_metTree->SetBranchAddress("hlt_pufit_met",&hlt_pufit_met);
  //Topocluster pileup subtraction (tc_lcw_pueta) 
  t_metTree->SetBranchAddress("hlt_pueta_met",&hlt_pueta_met);
  //Event Information
  t_metTree->SetBranchAddress("eventNumber",&eventNumber);
  t_metTree->SetBranchAddress("runNumber",&runNumber);
  t_metTree->SetBranchAddress("lumiBlock",&lumiBlock);
  t_metTree->SetBranchAddress("actualMu",&actualMu);
  t_metTree->SetBranchAddress("averageMu",&averageMu);
  t_metTree->SetBranchAddress("bunchCrossingID",&bunchCrossingID);
  t_metTree->SetBranchAddress("nPrimaryVtx",&nPrimaryVtx);
  //Bunch Information
  t_metTree->SetBranchAddress("distanceFromFront",&distanceFromFront);
  t_metTree->SetBranchAddress("distanceFromTail",&distanceFromTail);
  //Signal selection bools
  t_metTree->SetBranchAddress("passWenu",&passWenu);
  t_metTree->SetBranchAddress("passWmunu",&passWmunu);
  t_metTree->SetBranchAddress("passZee",&passZee);
  t_metTree->SetBranchAddress("passZmumu",&passZmumu);
  //Trigger passed bools
  t_metTree->SetBranchAddress("pass_HLT_xe100_L1XE50",&pass_HLT_xe100_L1XE50);
  t_metTree->SetBranchAddress("pass_HLT_xe110_mht_L1XE50",&pass_HLT_xe110_mht_L1XE50);
  t_metTree->SetBranchAddress("pass_HLT_xe160_tc_lcw_L1XE50",&pass_HLT_xe160_tc_lcw_L1XE50);
  t_metTree->SetBranchAddress("pass_HLT_xe140_pufit_L1XE50",&pass_HLT_xe140_pufit_L1XE50);
  t_metTree->SetBranchAddress("pass_HLT_xe140_pueta_L1XE50",&pass_HLT_xe140_pueta_L1XE50);
  t_metTree->SetBranchAddress("pass_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50",&pass_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50);

  //Book histograms
  //
  // book basic simple met hist
  h_offlineMET = new TH1D("h_offlineMET"," ;E_{T}^{miss} [GeV]", 50,0,400);
  h_highMu_offlineMET = new TH1D("h_highMu_offlineMET"," ;E_{T}^{miss} [GeV]", 50,0,400);
  h_lowMu_offlineMET = new TH1D("h_lowMu_offlineMET"," ;E_{T}^{miss} [GeV]", 50,0,400);
  h_hlt_cell_met = new TH1D("h_hlt_cell_met"," ;cell E_{T}^{miss} [GeV]", 50,0,400);
  h_hlt_mht_met = new TH1D("h_hlt_mht_met"," ;mht E_{T}^{miss} [GeV]", 50,0,400);
  h_hlt_topoCluster_met = new TH1D("h_hlt_topoCluster_met"," ;tc E_{T}^{miss} [GeV]", 50,0,400);
  h_hlt_pufit_met = new TH1D("h_hlt_pufit_met"," ;pufit E_{T}^{miss} [GeV]", 50,0,400);
  h_hlt_pueta_met = new TH1D("h_hlt_pueta_met"," ;pueta E_{T}^{miss} [GeV]", 50,0,400);


  // book hist for Efficiency
  h_offMET_HLT_xe100_L1XE50 = new TH1D("h_offMET_HLT_xe100_L1XE50"," ;h_offMET_HLT_xe100_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_offMET_HLT_xe110_mht_L1XE50 = new TH1D("h_offMET_HLT_xe110_mht_L1XE50"," ;h_offMET_HLT_xe110_mht_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_offMET_HLT_xe140_pufit_L1XE50 = new TH1D("h_offMET_HLT_xe140_pufit_L1XE50"," ;h_offMET_HLT_xe140_pufit_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 = new TH1D("h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50"," ;h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);

  h_highMu_offMET_HLT_xe100_L1XE50 = new TH1D("h_highMu_offMET_HLT_xe100_L1XE50"," ;h_highMu_offMET_HLT_xe100_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_highMu_offMET_HLT_xe110_mht_L1XE50 = new TH1D("h_highMu_offMET_HLT_xe110_mht_L1XE50"," ;h_highMu_offMET_HLT_xe110_mht_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_highMu_offMET_HLT_xe140_pufit_L1XE50 = new TH1D("h_highMu_offMET_HLT_xe140_pufit_L1XE50"," ;h_highMu_offMET_HLT_xe140_pufit_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 = new TH1D("h_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50"," ;h_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);

  h_lowMu_offMET_HLT_xe100_L1XE50 = new TH1D("h_lowMu_offMET_HLT_xe100_L1XE50"," ;h_lowMu_offMET_HLT_xe100_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_lowMu_offMET_HLT_xe110_mht_L1XE50 = new TH1D("h_lowMu_offMET_HLT_xe110_mht_L1XE50"," ;h_lowMu_offMET_HLT_xe110_mht_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_lowMu_offMET_HLT_xe140_pufit_L1XE50 = new TH1D("h_lowMu_offMET_HLT_xe140_pufit_L1XE50"," ;h_lowMu_offMET_HLT_xe140_pufit_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);
  h_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 = new TH1D("h_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50"," ;h_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 E_{T}^{miss} [GeV]", 50,0,400);

  //sample 2D correlation plots
  h2_offlineVscellMET = new TH2D("offlineVScellMet","offline vs  cell  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);E_{T}^{miss}, [GeV](offline, no #mu);  cell E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_mhtVscellMET = new TH2D("mhtVScellMet","mht vs  cell  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);mht E_{T}^{miss} [GeV];  cell E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_topoClusterVscellMET = new TH2D("topoClusterVScellMet","topoCluster vs  cell  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);tc E_{T}^{miss} [GeV];  cell E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_pufitVscellMET = new TH2D("pufitVScellMet","pufit vs  cell  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);pufit E_{T}^{miss} [GeV];  cell E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_puetaVscellMET = new TH2D("puetaVScellMet","pueta vs  cell  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);pueta E_{T}^{miss} [GeV];  cell E_{T}^{miss} [GeV]", 50,0,400,50,0,400);

  h2_offlineVsmhtMET = new TH2D("offlineVSmhtMET","offline vs  mht  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);E_{T}^{miss}, [GeV](offline, no #mu);  mht E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_cellVsmhtMET = new TH2D("cellVSmhtMET","cell vs mht MET (xAOD#rightarrow Ntuple#rightarrow Histogram);cell E_{T}^{miss} [GeV];  mht E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_topoClusterVsmhtMET = new TH2D("topoClusterVSmhtMET","topoCluster vs  mht  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);tc E_{T}^{miss} [GeV];  mht E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_pufitVsmhtMET = new TH2D("pufitVSmhtMET","pufit vs  mht  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);pufit E_{T}^{miss} [GeV];  mht E_{T}^{miss} [GeV]", 50,0,400,50,0,400);
  h2_puetaVsmhtMET = new TH2D("puetaVSmhtMET","pueta vs  mht  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);pueta E_{T}^{miss} [GeV];  mht E_{T}^{miss} [GeV]", 50,0,400,50,0,400);


  h2_offlineVspufitMET = new TH2D("offlineVSpufitMet","offline vs  pufit  MET (xAOD#rightarrow Ntuple#rightarrow Histogram);E_{T}^{miss}, [GeV](offline, no #mu);  pufit E_{T}^{miss} [GeV]", 50,0,400,50,0,400);


  //read all entries and fill the histograms
  //cout<<"before loop"<<endl;
  Long64_t nentries = t_metTree->GetEntries();
  for (Long64_t i=0;i<nentries;i++) {
    t_metTree->GetEntry(i);
    //TODO is there a way to do this outside the loop?/a better way? 
    bool eventSelected;
    if(signalSelection =="Wenu") eventSelected = passWenu; 
    if(signalSelection =="Wmunu") eventSelected = passWmunu; 
    if(signalSelection =="Zee") eventSelected = passZee; 
    if(signalSelection =="Zmumu") eventSelected = passZmumu; 

    //perform signal selection
    //TODO allow multiple sinal selection at the time, make hist for all selected
    if(eventSelected){ 
      h_offlineMET->Fill(offlineMET);
      h_hlt_cell_met->Fill(hlt_cell_met);
      h_hlt_mht_met->Fill(hlt_mht_met);
      h_hlt_topoCluster_met->Fill(hlt_topoCluster_met);
      h_hlt_pufit_met->Fill(hlt_pufit_met);
      h_hlt_pueta_met->Fill(hlt_pueta_met);

      //Example correlation histograms
      h2_offlineVscellMET->Fill(offlineMET,hlt_cell_met);
      h2_offlineVspufitMET->Fill(offlineMET,hlt_pufit_met);
      h2_mhtVscellMET->Fill(hlt_mht_met,hlt_cell_met);
      h2_topoClusterVscellMET->Fill(hlt_topoCluster_met,hlt_cell_met);
      h2_pufitVscellMET->Fill(hlt_pufit_met,hlt_cell_met);
      h2_puetaVscellMET->Fill(hlt_pueta_met,hlt_cell_met);

      h2_offlineVsmhtMET->Fill(offlineMET,hlt_mht_met);
      h2_cellVsmhtMET->Fill(hlt_cell_met,hlt_mht_met);
      h2_topoClusterVsmhtMET->Fill(hlt_topoCluster_met,hlt_mht_met);
      h2_pufitVsmhtMET->Fill(hlt_pufit_met,hlt_mht_met);

      //fill histograms for turn on curves
      if (pass_HLT_xe100_L1XE50)  h_offMET_HLT_xe100_L1XE50->Fill(offlineMET);
      if (pass_HLT_xe110_mht_L1XE50)  h_offMET_HLT_xe110_mht_L1XE50->Fill(offlineMET);
      if (pass_HLT_xe140_pufit_L1XE50)  h_offMET_HLT_xe140_pufit_L1XE50->Fill(offlineMET);
      if (pass_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50)  h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Fill(offlineMET);

      //Efficiencies with high and low pileup
      // work in progressif (averageMu >= 20){
      // work in progress  h_highMu_offlineMET->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe100_L1XE50)  h_highMu_offMET_HLT_xe100_L1XE50->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe110_mht_L1XE50)  h_highMu_offMET_HLT_xe110_mht_L1XE50->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe140_pufit_L1XE50)  h_highMu_offMET_HLT_xe140_pufit_L1XE50->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50)  h_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Fill(offlineMET);
      // work in progress}

      // work in progressif (averageMu <= 20){
      // work in progress  h_lowMu_offlineMET->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe100_L1XE50)  h_lowMu_offMET_HLT_xe100_L1XE50->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe110_mht_L1XE50)  h_lowMu_offMET_HLT_xe110_mht_L1XE50->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe140_pufit_L1XE50)  h_lowMu_offMET_HLT_xe140_pufit_L1XE50->Fill(offlineMET);
      // work in progress  if (pass_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50)  h_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Fill(offlineMET);
      // work in progress}

      if (i%50000 == 0) cout<<"processing event "<<i<<endl<<"offline/cell met: "<<offlineMET<<"  /  "<<hlt_cell_met<<endl;
    }
  }
  //cout<<"after loop"<<endl;
  
  //cout<<"before new file"<<endl;

  TFile *myFile = new TFile("metHistograms.root","recreate");
  //cout<<"after creating new file"<<endl;
  //Setting default colors for each
  h_offlineMET->SetLineColor(offCol);
  h_hlt_cell_met->SetLineColor(cellCol);
  h_hlt_mht_met->SetLineColor(mhtCol);
  h_hlt_pufit_met->SetLineColor(pufitCol);
  //
  h_offlineMET->Write();
  h_hlt_cell_met->Write();
  h_hlt_mht_met->Write();
  //h_hlt_topoCluster_met->Write();
  h_hlt_pufit_met->Write();
  //h_hlt_pueta_met->Write();

  h_offMET_HLT_xe100_L1XE50->Write();                     
  h_offMET_HLT_xe110_mht_L1XE50->Write();
  //h_offMET_HLT_xe160_tc_lcw_L1XE50->Write();
  h_offMET_HLT_xe140_pufit_L1XE50->Write();
  //h_offMET_HLT_xe140_pueta_L1XE50->Write();
  h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Write();

  h2_offlineVscellMET->Write();
  h2_offlineVspufitMET->Write();
  h2_mhtVscellMET->Write();
  h2_topoClusterVscellMET->Write();
  h2_pufitVscellMET->Write();
  h2_puetaVscellMET->Write();
  
  h2_offlineVsmhtMET->Write();
  h2_cellVsmhtMET->Write();
  h2_topoClusterVsmhtMET->Write();
  h2_pufitVsmhtMET->Write();
  h2_puetaVsmhtMET->Write();


  TFile *myEffFile = new TFile("metEfficiencies.root","recreate");
  //make cumulative efficiency curve
  //TEfficiency
  TGraphAsymmErrors* ef_offMET_HLT_xe100_L1XE50;
  TGraphAsymmErrors* ef_offMET_HLT_xe140_pufit_L1XE50;
  TGraphAsymmErrors* ef_offMET_HLT_xe110_mht_L1XE50;
  TGraphAsymmErrors* ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50;

  // work in progress TGraphAsymmErrors* ef_highMu_offMET_HLT_xe100_L1XE50;
  // work in progress TGraphAsymmErrors* ef_highMu_offMET_HLT_xe140_pufit_L1XE50;
  // work in progress TGraphAsymmErrors* ef_highMu_offMET_HLT_xe110_mht_L1XE50;
  // work in progress TGraphAsymmErrors* ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50;

  // work in progress TGraphAsymmErrors* ef_lowMu_offMET_HLT_xe100_L1XE50;
  // work in progress TGraphAsymmErrors* ef_lowMu_offMET_HLT_xe140_pufit_L1XE50;
  // work in progress TGraphAsymmErrors* ef_lowMu_offMET_HLT_xe110_mht_L1XE50;
  // work in progress TGraphAsymmErrors* ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50;


  // work in progress if(TEfficiency::CheckConsistency(*h_highMu_offMET_HLT_xe140_pufit_L1XE50->GetCumulative(kFALSE),*h_highMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_highMu_offMET_HLT_xe140_pufit_L1XE50 = new TGraphAsymmErrors(h_highMu_offMET_HLT_xe140_pufit_L1XE50->GetCumulative(kFALSE),h_highMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_highMu_offMET_HLT_xe140_pufit_L1XE50->SetName("ef_highMu_offMET_HLT_xe140_pufit_L1XE50"); 
  // work in progress   ef_highMu_offMET_HLT_xe140_pufit_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_highMu_offMET_HLT_xe140_pufit_L1XE50->SetLineColor(pufitCol); 
  // work in progress   ef_highMu_offMET_HLT_xe140_pufit_L1XE50->SetMarkerColor(pufitCol); 
  // work in progress   ef_highMu_offMET_HLT_xe140_pufit_L1XE50->Write(); 
  // work in progress }
  // work in progress if(TEfficiency::CheckConsistency(*h_highMu_offMET_HLT_xe110_mht_L1XE50->GetCumulative(kFALSE),*h_highMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50 = new TGraphAsymmErrors(h_highMu_offMET_HLT_xe110_mht_L1XE50->GetCumulative(kFALSE),h_highMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50->SetName("ef_highMu_offMET_HLT_xe110_mht_L1XE50"); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50->SetLineColor(mhtCol); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50->SetMarkerColor(mhtCol); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50->Write(); 
  // work in progress }
  // work in progress if(TEfficiency::CheckConsistency(*h_highMu_offMET_HLT_xe100_L1XE50->GetCumulative(kFALSE),*h_highMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_highMu_offMET_HLT_xe100_L1XE50 = new TGraphAsymmErrors(h_highMu_offMET_HLT_xe100_L1XE50->GetCumulative(kFALSE),h_highMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_highMu_offMET_HLT_xe100_L1XE50->SetName("ef_highMu_offMET_HLT_xe100_L1XE50"); 
  // work in progress   ef_highMu_offMET_HLT_xe100_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_highMu_offMET_HLT_xe100_L1XE50->SetLineColor(cellCol); 
  // work in progress   ef_highMu_offMET_HLT_xe100_L1XE50->SetMarkerColor(cellCol); 
  // work in progress   ef_highMu_offMET_HLT_xe100_L1XE50->Write(); 
  // work in progress }
  // work in progress if(TEfficiency::CheckConsistency(*h_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->GetCumulative(kFALSE),*h_highMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 = new TGraphAsymmErrors(h_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->GetCumulative(kFALSE),h_highMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetName("ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50"); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetLineColor(cellCol); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetMarkerColor(cellCol); 
  // work in progress   ef_highMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Write(); 
  // work in progress }

  // work in progress if(TEfficiency::CheckConsistency(*h_lowMu_offMET_HLT_xe140_pufit_L1XE50->GetCumulative(kFALSE),*h_lowMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_lowMu_offMET_HLT_xe140_pufit_L1XE50 = new TGraphAsymmErrors(h_lowMu_offMET_HLT_xe140_pufit_L1XE50->GetCumulative(kFALSE),h_lowMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_lowMu_offMET_HLT_xe140_pufit_L1XE50->SetName("ef_lowMu_offMET_HLT_xe140_pufit_L1XE50"); 
  // work in progress   ef_lowMu_offMET_HLT_xe140_pufit_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_lowMu_offMET_HLT_xe140_pufit_L1XE50->SetLineColor(pufitCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe140_pufit_L1XE50->SetMarkerColor(pufitCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe140_pufit_L1XE50->Write(); 
  // work in progress }
  // work in progress if(TEfficiency::CheckConsistency(*h_lowMu_offMET_HLT_xe110_mht_L1XE50->GetCumulative(kFALSE),*h_lowMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50 = new TGraphAsymmErrors(h_lowMu_offMET_HLT_xe110_mht_L1XE50->GetCumulative(kFALSE),h_lowMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50->SetName("ef_lowMu_offMET_HLT_xe110_mht_L1XE50"); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50->SetLineColor(mhtCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50->SetMarkerColor(mhtCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50->Write(); 
  // work in progress }
  // work in progress if(TEfficiency::CheckConsistency(*h_lowMu_offMET_HLT_xe100_L1XE50->GetCumulative(kFALSE),*h_lowMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_lowMu_offMET_HLT_xe100_L1XE50 = new TGraphAsymmErrors(h_lowMu_offMET_HLT_xe100_L1XE50->GetCumulative(kFALSE),h_lowMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_lowMu_offMET_HLT_xe100_L1XE50->SetName("ef_lowMu_offMET_HLT_xe100_L1XE50"); 
  // work in progress   ef_lowMu_offMET_HLT_xe100_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_lowMu_offMET_HLT_xe100_L1XE50->SetLineColor(cellCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe100_L1XE50->SetMarkerColor(cellCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe100_L1XE50->Write(); 
  // work in progress }
  // work in progress if(TEfficiency::CheckConsistency(*h_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->GetCumulative(kFALSE),*h_lowMu_offlineMET->GetCumulative(kFALSE))) 
  // work in progress { 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 = new TGraphAsymmErrors(h_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->GetCumulative(kFALSE),h_lowMu_offlineMET->GetCumulative(kFALSE)); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetName("ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50"); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetLineColor(cellCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetMarkerColor(cellCol); 
  // work in progress   ef_lowMu_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Write(); 
  // work in progress }

  if(TEfficiency::CheckConsistency(*h_offMET_HLT_xe140_pufit_L1XE50->GetCumulative(kFALSE),*h_offlineMET->GetCumulative(kFALSE))) 
  { 
    ef_offMET_HLT_xe140_pufit_L1XE50 = new TGraphAsymmErrors(h_offMET_HLT_xe140_pufit_L1XE50->GetCumulative(kFALSE),h_offlineMET->GetCumulative(kFALSE)); 
    ef_offMET_HLT_xe140_pufit_L1XE50->SetName("ef_offMET_HLT_xe140_pufit_L1XE50"); 
    ef_offMET_HLT_xe140_pufit_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
    ef_offMET_HLT_xe140_pufit_L1XE50->SetLineColor(pufitCol); 
    ef_offMET_HLT_xe140_pufit_L1XE50->SetMarkerColor(pufitCol); 
    ef_offMET_HLT_xe140_pufit_L1XE50->Write(); 
  }
  if(TEfficiency::CheckConsistency(*h_offMET_HLT_xe110_mht_L1XE50->GetCumulative(kFALSE),*h_offlineMET->GetCumulative(kFALSE))) 
  { 
    ef_offMET_HLT_xe110_mht_L1XE50 = new TGraphAsymmErrors(h_offMET_HLT_xe110_mht_L1XE50->GetCumulative(kFALSE),h_offlineMET->GetCumulative(kFALSE)); 
    ef_offMET_HLT_xe110_mht_L1XE50->SetName("ef_offMET_HLT_xe110_mht_L1XE50"); 
    ef_offMET_HLT_xe110_mht_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
    ef_offMET_HLT_xe110_mht_L1XE50->SetLineColor(mhtCol); 
    ef_offMET_HLT_xe110_mht_L1XE50->SetMarkerColor(mhtCol); 
    ef_offMET_HLT_xe110_mht_L1XE50->Write(); 
  }
  if(TEfficiency::CheckConsistency(*h_offMET_HLT_xe100_L1XE50->GetCumulative(kFALSE),*h_offlineMET->GetCumulative(kFALSE))) 
  { 
    ef_offMET_HLT_xe100_L1XE50 = new TGraphAsymmErrors(h_offMET_HLT_xe100_L1XE50->GetCumulative(kFALSE),h_offlineMET->GetCumulative(kFALSE)); 
    ef_offMET_HLT_xe100_L1XE50->SetName("ef_offMET_HLT_xe100_L1XE50"); 
    ef_offMET_HLT_xe100_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
    ef_offMET_HLT_xe100_L1XE50->SetLineColor(cellCol); 
    ef_offMET_HLT_xe100_L1XE50->SetMarkerColor(cellCol); 
    ef_offMET_HLT_xe100_L1XE50->Write(); 
  }
  if(TEfficiency::CheckConsistency(*h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->GetCumulative(kFALSE),*h_offlineMET->GetCumulative(kFALSE))) 
  { 
    ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50 = new TGraphAsymmErrors(h_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->GetCumulative(kFALSE),h_offlineMET->GetCumulative(kFALSE)); 
    ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetName("ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50"); 
    ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetTitle(";E_{Tmiss} [GeV] (offline, no #mu); Cumulative Efficiency"); 
    ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetLineColor(cellCol); 
    ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->SetMarkerColor(cellCol); 
    ef_offMET_HLT_xe110_mht_L1XE50_AND_xe70_L1XE50->Write(); 
  }

  myEffFile->Close();

  //cout<<"closing new file"<<endl;
  myFile->Close();
  //cout<<"after new file"<<endl;
  f->Close();
}

